<a href="https://colab.research.google.com/github/SrinivasanNikhil/DataLiteracy/blob/master/Numpy_Concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy is a Python library that is used for working with arrays. This library contains a vareity of routines/functions for processing these arrays. These arrays can  have one or multiple dimensions. 

Numpy also has a collection of routines/functions related to linear algebra, fourier transforms and shape manipulation. 

## Using numpy

To utilize numpy in your python script one needs to import it using the import statement as below

In [ ]:
import numpy as np #the as clause clause creates an alias

## Working with numpy arrays

The array object in numpy is known as ndarray. It is creating used the array() function within numpy.

In [ ]:
import numpy as np

anArr = np.array([1,2,3,4,5,6])

print(type(anArr))

print(anArr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [ ]:
# One can convert lists and tuples into numpy arrays
import numpy as np

aList = ["Nikhil","Akhil","Maric","Karen","Aaron"]
anArr = np.array(aList)

print(type(aList))
print(type(anArr))
print(aList)
print(anArr)


<class 'list'>
<class 'numpy.ndarray'>
['Nikhil', 'Akhil', 'Maric', 'Karen', 'Aaron']
['Nikhil' 'Akhil' 'Maric' 'Karen' 'Aaron']


## Array attributes

1. shape - array.shape returns a tuple consisting of the arrays dimensions

2. ndim - array.ndim returns the number of docemsions for the array

...more

## Array concepts

1. Indexing - very similat to list indexing in python. Arrays start at the 0 position. Arrays also use negative indexing. 

2. Slicing - Slicing means to extract elements from an array from one index to another. 




In [ ]:
#Indexing
import numpy as np

names = np.array(["Nikhil","Akhil","Maric","Karen","Aaron","Shiela"])

print(names[1])

#Slicing

print(names[2:])

print(names[2:6:2])



Akhil
['Maric' 'Karen' 'Aaron' 'Shiela']
['Maric' 'Aaron']


3. Array Copy - creates a new copy of the array. Any changes made to the copy will not affect the original array. 
4. Array View - does not create a copy and any changes made t the view will influence and affect the original array and vice versa. 

In [ ]:
import numpy as np

anArr = np.array([1,2,3,4,5,6,7,8,9,10])

x = anArr.copy()

x[2] = 32

print(anArr)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2 32  4  5  6  7  8  9 10]


In [ ]:
import numpy as np

anArr = np.array([1,2,3,4,5,6,7,8,9,10])

x = anArr.view()

x[2] = 32

print(anArr)
print(x)

[ 1  2 32  4  5  6  7  8  9 10]
[ 1  2 32  4  5  6  7  8  9 10]


## Iterating over an array

Go over the elements of the array one by one.

In [ ]:
import numpy as np

anArr = np.array([1,2,3,4,5,6,7,8,9,10])

for x in anArr:
  print(x)

1
2
3
4
5
6
7
8
9
10


## Joining Arrays

When arrays are joined together the contents of 2 or more arrays are put together in a single array. This is accomplished through the use of the concatenate function.

Can also be acomplished using the following
*   stack() - done along axis of choice
*   hstack() - stacking along rows
*   vstack() - stacking along columns
*   dstack() - stacking along depth



In [ ]:
import numpy as np
num1 = np.array([1,2,3,4])
num2 = np.array([12,13,14,15,16])

num = np.concatenate((num1,num2))
print(num)

names = np.array(["Nikhil","Akhil","Maric","Karen","Aaron","Shiela"])


num = np.concatenate((num1,num2,names))
print(num)


[ 1  2  3  4 12 13 14 15 16]
['1' '2' '3' '4' '12' '13' '14' '15' '16' 'Nikhil' 'Akhil' 'Maric' 'Karen'
 'Aaron' 'Shiela']


## Splitting an array

Array's can be split into smaller arrays using the array_split() function

In [ ]:
import numpy as np
names = np.array(["Nikhil","Akhil","Maric","Karen","Aaron","Shiela"])

namesSplit = np.array_split(names,2)

print(namesSplit)

[array(['Nikhil', 'Akhil', 'Maric'], dtype='<U6'), array(['Karen', 'Aaron', 'Shiela'], dtype='<U6')]


## Searching an array

An array can be searched for values and the result returned are the index positions in the array where the search term was found. 

In [ ]:
import numpy as np
names = np.array(["Nikhil","Akhil","Maric","Karen","Aaron","Maric", "Jim","Jordan","Maric"])


x = np.where((names == "Maric"))
print(x)

(array([2, 5, 8]),)


## Sorting an array

An array can be srted into an ordered sequnce using the sort function. The sorting does not change the array but provides a new array of sorted elements.

In [ ]:
import numpy as np
names = np.array(["Nikhil","Akhil","Maric","Karen","Aaron","Maric", "Jim","Jordan","Maric"])

print(np.sort(names))

['Aaron' 'Akhil' 'Jim' 'Jordan' 'Karen' 'Maric' 'Maric' 'Maric' 'Nikhil']


## Filtering

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.


### Creating Filter Directly From Array

The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [1]:
import numpy as np

names = np.array(["Mark", "Craig","Mary","Sam","Jim","Emily"])

filter_arr = [True, True, False, False, False, True]

x = names[filter_arr]

print(x)

['Mark' 'Craig' 'Emily']


In [3]:
import numpy as np

arr = np.array([3.2,4.0,2.3,3.1,2.99,3.7,3.9])

filter_arr = arr > 3.2

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False False False  True  True]
[4.  3.7 3.9]
